### PR TITLE
Feature/add shoal mask

### PR DESCRIPTION
**Pull request by ruxandra-valcu**

### CODE REVIEW

**Review by beatfactor — APPROVED** [review]

**Review by mihaiboldeanu — CHANGES_REQUESTED** [review]
I think its is easier to have a function called get_shoal_mask() as it is easier to understand what it does compared to directly calling weil().
For all of the other masking algorithm we had a convention of get_"noise_type"_mask() wrapper function over the specific implementation(ryan(),ariza(), etc.).

**Comment by ruxandra-valcu** [comment]
> I think its is easier to have a function called get_shoal_mask() as it is easier to understand what it does compared to directly calling weil(). For all of the other masking algorithm we had a convention of get_"noise_type"_mask() wrapper function over the specific implementation(ryan(),ariza(), etc.).

Added

**Review by mihaiboldeanu — APPROVED** [review]
Looks great!

**Comment by ruxandra-valcu** [comment]
TODO, after Wu Jung Lee's comments to our PR:

- [ ] move weill to echopype/mask/shoal.py, rename as private
- [ ] move get_shoal_mask to echopype/mask/api.py
- [ ] test setup part should now use pytest fixtures and be in tests/clean/conftest.py and requested by the test modules

**Comment by ruxandra-valcu** [comment]
Closing since no longer part of our workflow

**Pull request closed without merging**
