### PR TITLE
Merge/add multichannel masks

### PR DESCRIPTION
**Pull request by ruxandra-valcu**
Added multichannel mask support to apply_mask - if a channelless or single-channel mask is provided it'll apply it to all channels of the dataset, whereas if a mask with multiple channels is provided, it'll apply each channel of the mask to the corresponding channel individually.

### CODE REVIEW

**Comment by simedroniraluca** [comment]
Is it safe to apply a single-channel mask across all channels if no specific mask is designed for each individual channel?

**Comment by simedroniraluca** [comment]
If you enhanced the functionality of apply_mask, shouldn't you also update the modified function's documentation?

**Review by simedroniraluca — APPROVED** [review]

**Comment by ruxandra-valcu** [comment]
> Is it safe to apply a single-channel mask across all channels if no specific mask is designed for each individual channel?

This is the previous behaviour of the function - if you give it a mask with channels, it just applies channel 0 to everything

**Comment by ruxandra-valcu** [comment]
> If you enhanced the functionality of apply_mask, shouldn't you also update the modified function's documentation?

Updated

**Pull request merged**
